# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: George B
title: Principal Architect / Enterprise Architect
email: george.itmatters@gmail.com
website: https://georgebcodegit.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# github_username:
# linkedin_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is George and I'm a Principal Architect. I have technical hand-on experience in implementations and migrations of SAP solutions, and architecture experience in Cloud Architecture, Cyber Security, SAP solutions, integrations and applications. 

  My domain experience includes: Banking, Investment Banking, Public and Private sector industries. 

  My technical skills includes - SAP ABAP, SOA, SOAP & REST services, FIORI,Java Script, Python, SAP SAC, BTP, Business Process Automation, Extensions and Enhancements, Cloud security assessments and Machine Learning. 
  Additionally, I have experience in SAP SuccessFactors, SAP BTP, SAP SAC, SAP S/4HANA, SAP Core Banking, SAP Payments Engine and SAP Datasphere.

  I am most skilled in: <mark>SAP Solution Architecture</mark>, <mark>SAP Technical Architecture</mark>, <mark>SAP Integration Architecture</mark> and <mark>SAP Implementations</mark>.

  My certifications includes: <mark>SAP Banking</mark>, <mark>AWS</mark> and <mark>TOGAF</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border: weak # Value of `weak` will display a weak border below this item
        title: SAP
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Enterprise Cloud Architect
        caption: November 2020- Present
        quote: >
          Cloud Architecture, Cyber and Information Security, Solution Architecture, Migrations to S/4HANA and SuccessFactors, Partner Engagement, Customer Facing, Pre-sales engagements, Stakeholder management, Workshops, Roadmaps, Capability and Enterprise Architecture.
        description: | # this will include new lines to allow paragraphs
          Delivered on architecture of SaaS, PaaS and IaaS based cloud solution, and cyber security assessments for the software and platform solutions. Designed cloud solution for complex customer requests, conducted workshops to upskill partners and customers on various solution, application, integration, data warehouse, analytics and machine learning capabilities. Also, provided solution on migration approach and provided customer and partner migration planning workshop to impart knowledge on migration from on-prem to cloud based solutions.

          Train and mentor interns and new team members in team on business aread, products and technologies

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SAP
        # sub_title: CBA
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: |
          Principal Architect       

          CBA
        caption: February 2019 - November 2021
        quote: >
          Core Banking, Commercial Lending, Migration, Upgrade, SOA, REST, PI/PO, API, ABAP, BADI, Payments, Loans and Accounts Management, Financial Accounting, Analytical Banking, Stakeholder mangement, Requirement gathering, Architecture review, Code review, Deployment, Support
        description: | # this will include new lines to allow paragraphs
          Hands-on experience in SAP Core Banking release upgrade project and remediate post go-live priority issues. 

          As an Architect worked with 

          - key business stakeholders in gathering requirements, 
          - solution and techncial archtecture team in designing new solutions and reviewing solution designs, 
          - monitor code quality, sign-off on the deliverable and deployment executed by the SI partner
          - Engage in API roadmap for Open Banking initiatives

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SAP
        # sub_title: Macquarie Bank
        sub_title: Principal Architect    Macquarie Bank
        caption: January 2014 - February 2019
        quote: >
          Core Banking, Retail Lending, API, ABAP, BADI, REST, OData, PI/PO, Payments, Loans and Accounts Management, Financial Accounting, CRM, Stakeholder mangement, Requirement gathering, Architecture review, Governance, Code review, Deployment, Support
        description: | # this will include new lines to allow paragraphs
          Hands-on experience in SAP Core Banking greenfield implementation, from setting up the system from scratch, to system architecture, setting up of application development and integration framework and governance and best practices. 

          As an architect and principal consultant, participated in various roles and responsibilites within the customer. Key roles and responsibilities included:

          - member of the ARB representing SAP in setting up strategice roadmaps and key decision making activities
          - key business stakeholders/product owners in gathering requirements while working in an Agile environment, 
          - lead solution and techncial archtecture team in designing new solutions and reviewing solution designs, 
          - orchestrate and automate business process, and integrate using middleware technology with channel applications
          - solution design - accounts origination, transaction and savings account, retail loans implementation, implement and integrate collateral management

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SAP
        # sub_title: Macquarie Bank
        sub_title: Senior Architect    CBA
        caption: February 2010 - January 2014
        quote: >
          Core Banking, Commercial Lending, Migration, SOA, REST, PI/PO, API, ABAP, BADI, Payments, Loans and Accounts Management, Financial Accounting, Analytical Banking, Stakeholder mangement, Requirement gathering, Architecture review, Code review, Design, Implementation, Deployment and Support
        description: | # this will include new lines to allow paragraphs
          As a SAP Technical architect and SME implemented Core Banking solutions focused on Payments, Analytical Banking and Loans Management areas.  

          Participated in various roles and responsibilites within the customer, including:
          - migration from legacy to SAP Core Banking.
          - implementation of multiple payment solutions and features and integrations 
          - key business stakeholders/product owners in gathering requirements
          - lead technical team and collaborate with business on requirements and deliverables

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SAP Labs
        sub_title: Principal Software Engineer
        caption: July 2007 - January 2010
        quote: >
          Banking Services, Payments Engine, Deposits , Accounts, Loans, Treasury and Risk Management
        description: | # this will include new lines to allow paragraphs
          As a SAP Product development specialist, worked across various product development opportunities within SAP Core Banking (Deposits, Accounts, Payments and Loans Management) and Treasury and Risk Management.

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HCL Technologies (Canada)
        sub_title: Senior Software Engineer
        caption: Sep 2006 - July 2007
        quote: >
          SAP ERP, Supply Chain, Material Management, Finance, Quality Management
        description: | # this will include new lines to allow paragraphs
          As an on-site and ALE/IDoc expert was part of the implementation and maintenane project, with the following responsibilities:
          - lead offshore team in driving outcome
          - manage stakeholders and gather business requirements
          = design, review and deliver solutions related to ALV, BDC, SAP Scripts, LSMW and enhancements

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Siemens
        sub_title: Software Engineer  [SAP Labs]
        caption: Oct 2005 - Sep 2006
        quote: >
          SAP Banking Services, Transaction Banking (TRBK)
        description: | # this will include new lines to allow paragraphs
          Participated in design and development of SAP Banking Services on Newtweaver

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Goldman Sachs
        sub_title: Technology Analyst
        caption: Jan 2004 - Oct 2005
        quote: >
          Investment Banking, Application Packaging, CMS
        description: | # this will include new lines to allow paragraphs
          Participated in design of infrastructure blueprints, application packaging of software, system maintenance, and maintain internal reporting team site.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NIST
        caption: 1998 - 2002
        sub_title: Bachelor of Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Electrical and Electronics

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Fishing
      - Gaming
      - Cooking
      - Travelling

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
